// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace MagentoNetFE.MagentoNetService {

//MagentoNetFE.MagentoNetService
	[System.ServiceModel.ServiceContractAttribute(Namespace="http://tempuri.org/", ConfigurationName="ICategoryContract")]
public interface ICategoryContract {
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICategoryContract/SubmitEval", ReplyAction="http://tempuri.org/ICategoryContract/SubmitEvalResponse")]
    bool SubmitEval(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICategoryContract/SubmitEval", ReplyAction="http://tempuri.org/ICategoryContract/SubmitEvalResponse", AsyncPattern=true)]
    System.IAsyncResult BeginSubmitEval(int id, System.AsyncCallback asyncCallback, object userState);
    
    bool EndSubmitEval(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICategoryContract/GetTestString", ReplyAction="http://tempuri.org/ICategoryContract/GetTestStringResponse")]
    string GetTestString();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICategoryContract/GetTestString", ReplyAction="http://tempuri.org/ICategoryContract/GetTestStringResponse", AsyncPattern=true)]
    System.IAsyncResult BeginGetTestString(System.AsyncCallback asyncCallback, object userState);
    
    string EndGetTestString(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICategoryContract/GetCatItem", ReplyAction="http://tempuri.org/ICategoryContract/GetCatItemResponse")]
    GetCatItemResult GetCatItem(int Id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICategoryContract/GetCatItem", ReplyAction="http://tempuri.org/ICategoryContract/GetCatItemResponse", AsyncPattern=true)]
    System.IAsyncResult BeginGetCatItem(int Id, System.AsyncCallback asyncCallback, object userState);
    
    GetCatItemResult EndGetCatItem(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICategoryContract/GetCats", ReplyAction="http://tempuri.org/ICategoryContract/GetCatsResponse")]
    GetCatItemResult[] GetCats();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICategoryContract/GetCats", ReplyAction="http://tempuri.org/ICategoryContract/GetCatsResponse", AsyncPattern=true)]
    System.IAsyncResult BeginGetCats(System.AsyncCallback asyncCallback, object userState);
    
    GetCatItemResult[] EndGetCats(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICategoryContract/RemoveEval", ReplyAction="http://tempuri.org/ICategoryContract/RemoveEvalResponse")]
    bool RemoveEval(string id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICategoryContract/RemoveEval", ReplyAction="http://tempuri.org/ICategoryContract/RemoveEvalResponse", AsyncPattern=true)]
    System.IAsyncResult BeginRemoveEval(string id, System.AsyncCallback asyncCallback, object userState);
    
    bool EndRemoveEval(System.IAsyncResult result);
}

public interface ICategoryContractChannel : ICategoryContract, System.ServiceModel.IClientChannel {
}

public class CategoryContractClient : System.ServiceModel.ClientBase<ICategoryContract>, ICategoryContract {
    
    public CategoryContractClient() {
    }
    
    public CategoryContractClient(string endpointConfigurationName) : 
            base(endpointConfigurationName) {
    }
    
    public CategoryContractClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress) {
    }
    
    public CategoryContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress) {
    }
    
    public CategoryContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress endpoint) : 
            base(binding, endpoint) {
    }
    
    public bool SubmitEval(int id) {
        return base.Channel.SubmitEval(id);
    }
    
    public System.IAsyncResult BeginSubmitEval(int id, System.AsyncCallback asyncCallback, object userState) {
        return base.Channel.BeginSubmitEval(id, asyncCallback, userState);
    }
    
    public bool EndSubmitEval(System.IAsyncResult result) {
        return base.Channel.EndSubmitEval(result);
    }
    
    public string GetTestString() {
        return base.Channel.GetTestString();
    }
    
    public System.IAsyncResult BeginGetTestString(System.AsyncCallback asyncCallback, object userState) {
        return base.Channel.BeginGetTestString(asyncCallback, userState);
    }
    
    public string EndGetTestString(System.IAsyncResult result) {
        return base.Channel.EndGetTestString(result);
    }
    
    public GetCatItemResult GetCatItem(int Id) {
        return base.Channel.GetCatItem(Id);
    }
    
    public System.IAsyncResult BeginGetCatItem(int Id, System.AsyncCallback asyncCallback, object userState) {
        return base.Channel.BeginGetCatItem(Id, asyncCallback, userState);
    }
    
    public GetCatItemResult EndGetCatItem(System.IAsyncResult result) {
        return base.Channel.EndGetCatItem(result);
    }
    
    public GetCatItemResult[] GetCats() {
        return base.Channel.GetCats();
    }
    
    public System.IAsyncResult BeginGetCats(System.AsyncCallback asyncCallback, object userState) {
        return base.Channel.BeginGetCats(asyncCallback, userState);
    }
    
    public GetCatItemResult[] EndGetCats(System.IAsyncResult result) {
        return base.Channel.EndGetCats(result);
    }
    
    public bool RemoveEval(string id) {
        return base.Channel.RemoveEval(id);
    }
    
    public System.IAsyncResult BeginRemoveEval(string id, System.AsyncCallback asyncCallback, object userState) {
        return base.Channel.BeginRemoveEval(id, asyncCallback, userState);
    }
    
    public bool EndRemoveEval(System.IAsyncResult result) {
        return base.Channel.EndRemoveEval(result);
    }
}
}
namespace MagentoNetFE.MagentoNetService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CatalogCategory", Namespace="http://schemas.datacontract.org/2004/07/MagentoNetService")]
    public partial class GetCatItemResult : System.Runtime.Serialization.IExtensibleDataObject {
        
        private string AllChildrenField;
        
        private string AvailableSortByField;
        
        private string ChildrenField;
        
        private int? ChildrenCountField;
        
        private string CustomApplyToProductsField;
        
        private string CustomDesignField;
        
        private string CustomDesignFromField;
        
        private string CustomDesignToField;
        
        private string CustomLayoutUpdateField;
        
        private string CustomUseParentSettingsField;
        
        private string DefaultSortByField;
        
        private string DescriptionField;
        
        private string DisplayModeField;
        
        private string FilterPriceRangeField;
        
        private int? IdField;
        
        private string ImageField;
        
        private bool IncludeInMenuField;
        
        private bool IsActiveField;
        
        private bool IsAnchorField;
        
        private string LandingPageField;
        
        private string LevelField;
        
        private string MetaDescriptionField;
        
        private string MetaKeywordsField;
        
        private string MetaTitleField;
        
        private string NameField;
        
        private string PageLayoutField;
        
        private string PathField;
        
        private string PathInStoreField;
        
        private string PositionField;
        
        private System.DateTime TimeSubmittedField;
        
        private string UrlKeyField;
        
        private string UrlPathField;
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public virtual string AllChildren {
            get {
                return this.AllChildrenField;
            }
            set {
                this.AllChildrenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public virtual string AvailableSortBy {
            get {
                return this.AvailableSortByField;
            }
            set {
                this.AvailableSortByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public virtual string Children {
            get {
                return this.ChildrenField;
            }
            set {
                this.ChildrenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public virtual int? ChildrenCount {
            get {
                return this.ChildrenCountField;
            }
            set {
                this.ChildrenCountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public virtual string CustomApplyToProducts {
            get {
                return this.CustomApplyToProductsField;
            }
            set {
                this.CustomApplyToProductsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public virtual string CustomDesign {
            get {
                return this.CustomDesignField;
            }
            set {
                this.CustomDesignField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public virtual string CustomDesignFrom {
            get {
                return this.CustomDesignFromField;
            }
            set {
                this.CustomDesignFromField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public virtual string CustomDesignTo {
            get {
                return this.CustomDesignToField;
            }
            set {
                this.CustomDesignToField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public virtual string CustomLayoutUpdate {
            get {
                return this.CustomLayoutUpdateField;
            }
            set {
                this.CustomLayoutUpdateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public virtual string CustomUseParentSettings {
            get {
                return this.CustomUseParentSettingsField;
            }
            set {
                this.CustomUseParentSettingsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public virtual string DefaultSortBy {
            get {
                return this.DefaultSortByField;
            }
            set {
                this.DefaultSortByField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public virtual string Description {
            get {
                return this.DescriptionField;
            }
            set {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public virtual string DisplayMode {
            get {
                return this.DisplayModeField;
            }
            set {
                this.DisplayModeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public virtual string FilterPriceRange {
            get {
                return this.FilterPriceRangeField;
            }
            set {
                this.FilterPriceRangeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public virtual int? Id {
            get {
                return this.IdField;
            }
            set {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public virtual string Image {
            get {
                return this.ImageField;
            }
            set {
                this.ImageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public virtual bool IncludeInMenu {
            get {
                return this.IncludeInMenuField;
            }
            set {
                this.IncludeInMenuField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public virtual bool IsActive {
            get {
                return this.IsActiveField;
            }
            set {
                this.IsActiveField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public virtual bool IsAnchor {
            get {
                return this.IsAnchorField;
            }
            set {
                this.IsAnchorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public virtual string LandingPage {
            get {
                return this.LandingPageField;
            }
            set {
                this.LandingPageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public virtual string Level {
            get {
                return this.LevelField;
            }
            set {
                this.LevelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public virtual string MetaDescription {
            get {
                return this.MetaDescriptionField;
            }
            set {
                this.MetaDescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public virtual string MetaKeywords {
            get {
                return this.MetaKeywordsField;
            }
            set {
                this.MetaKeywordsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public virtual string MetaTitle {
            get {
                return this.MetaTitleField;
            }
            set {
                this.MetaTitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public virtual string Name {
            get {
                return this.NameField;
            }
            set {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public virtual string PageLayout {
            get {
                return this.PageLayoutField;
            }
            set {
                this.PageLayoutField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public virtual string Path {
            get {
                return this.PathField;
            }
            set {
                this.PathField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public virtual string PathInStore {
            get {
                return this.PathInStoreField;
            }
            set {
                this.PathInStoreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public virtual string Position {
            get {
                return this.PositionField;
            }
            set {
                this.PositionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public virtual System.DateTime TimeSubmitted {
            get {
                return this.TimeSubmittedField;
            }
            set {
                this.TimeSubmittedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public virtual string UrlKey {
            get {
                return this.UrlKeyField;
            }
            set {
                this.UrlKeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public virtual string UrlPath {
            get {
                return this.UrlPathField;
            }
            set {
                this.UrlPathField = value;
            }
        }
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
    }
}
