#!/bin/sh -e
NAME=magentonetservice
PATH_BIN=/bin:/usr/bin:/sbin:/usr/sbin
DAEMON="/home/dizimatt/Documents/mono/MagentoNet/MagentoNetService/init-startMagentoNetService.sh"
PIDFILE=/var/run/$NAME.pid
DEFAULTS=/etc/default/$NAME
DESC="magentonetservice daemon"

ENV="env -i LANG=C PATH=$PATH_BIN"

. /lib/lsb/init-functions

test -x $DAEMON || exit 0

[ -r "$DEFAULTS" ] && . "$DEFAULTS" || start_magentonetservice_daemon=yes

check_daemon_enabled () {
    if [ "$start_magentonetservice_daemon" = "yes" ] ; then
        return 0
    else
        log_warning_msg "Not starting $NAME daemon, disabled via /etc/default/$NAME"
        return 1
    fi

}

case "$1" in
  start)
    if check_daemon_enabled ; then
        if ! [ -d /var/run/magentonetservice ]; then
                mkdir /var/run/magentonetservice
        fi

        log_daemon_msg "Starting $DESC" "$NAME" 
	if start-stop-daemon --start --oknodo -n $NAME --exec $DAEMON -b ; then
            log_end_msg 0
        else
            log_end_msg 1
            RET=1
        fi
    fi
    ;;

  stop)
    log_daemon_msg "Stopping $DESC" "$NAME"
        for i in $(ps aux | grep -v grep | grep 'MagentoNetService.exe' | cut -c 10-15)
        do
                kill $i > /dev/null 2>&1
        done
        log_end_msg $?
        ;;

  *)
    echo "Usage: /etc/init.d/$NAME {start|stop|restart|reload}"
    RET=1
    ;;
esac


exit $RET
